[package]
name = "rxd"
description = "A hex dump written in Rust"
authors = ["StoatSec <stoatsec@proton.me>"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
regex = "1.10.6"